# Generated by Django 4.2.1 on 2023-06-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0, verbose_name='Movie rating'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='number_of_rating',
            field=models.IntegerField(default=0, verbose_name='Movie number of rating'),
        ),
    ]
